site_name: OncoRisk Documentation
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue
nav:
  - Home: index.md
  - 'Module 1: Knowledge Base & Query': module1_knowledge_query.md
  - 'Module 2: Somatic VCF Analysis': module2_somatic_analysis.md
  - 'Module 3: Pan-Cancer Visualizer': module3_pancancer_visual.md
  - 'Module 4: Server-Maftools': module4_maftools.md